# Site settings
title: "#proglangdesign"
description: > # this means to ignore newlines until "baseurl:"
  A website for the #proglangdesign community on freenode
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.proglangdesign.net" # the base hostname & protocol for your site
github_username: proglangdesign
encoding: UTF-8
repository: proglangdesign/proglangdesign.github.io

# Build settings
markdown: kramdown
strict_front_matter: true

# Exclude from processing.
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
